### ISSUE TITLE
FAIRSeq Post Process No Need 'tr' Command

### ISSUE THREAD

**Issue by Jason-Young-AI** [ictnlp/awesome-transformer#1]
For Latin-family languages, tr -d ' ' may lead to the error.
Not:
`grep ^H pred.de | cut -f1,3- | cut -c3- | sort -k1n | cut -f2- | tr -d ' ' > pred.de`
I think may be:
`grep ^H pred.de | cut -f1,3- | cut -c3- | sort -k1n | cut -f2- > pred.de`

**Comment by SkyAndCloud** [comment]
Already fixed. Thank you.

**Comment by Jason-Young-AI** [comment]
@SkyAndCloud No thanks. This issue can be closed.
