### ISSUE TITLE
After postprocess in fairseq, how about bleu score?

### ISSUE THREAD

**Issue by ElliottYan** [ictnlp/awesome-transformer#2]
Hi,
Thanks for these very helpful advices on reproducing WMT14 results. I followed all process for fairseq, but get confused when trying to get the final or "moderate" increased bleu score. After spliting the compound word, can you provide a process for scoring the translation? thanks.

**Comment by SkyAndCloud** [comment]
Hi, calculate BLEU of translation should be the same. Note that you should split compound word on both reference and hypothesis before scoring BLEU, see [get_ende_bleu.sh](https://github.com/tensorflow/tensor2tensor/blob/94477898f3a862654f045a2ba90e8a5848037cfd/tensor2tensor/utils/get_ende_bleu.sh#L18) for more details.

**Comment by SkyAndCloud** [comment]
I have updated doc for sacrebleu usage
